const os= require('node:os')

console.log('Informacion del sistema operativo: ') 
console.log('-------------------------------------')
console.log('Nombre del sistema operativo: ' + os.platform())
console.log('Version del sistema operativo: ' + os.version())
console.log('Arquitectura del sistema operativo: ' + os.arch())
console.log('CPus', os.cpus())
console.log('Memoria total: ' + os.totalmem() + ' bytes')
console.log('Memoria libre: ' + os.freemem() + ' bytes')
console.log('uptime: ' + os.uptime() /60/60)